CREATE SEQUENCE id_calendrier_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
CREATE SEQUENCE id_evenement_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 CREATE SEQUENCE id_transaction_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
