CREATE TABLE PARTICIPANTSTRANSACION
(IDPARTICIPANTTRANSACTION int not null ,
IDUTILISATEUR varchar2(50) not null,
IDTRANSACTION varchar2(50) not null,
MONTANT float
)
;


ALTER TABLE PARTICIPANTSTRANSACION
  ADD (
    CONSTRAINT PARTICIPANTTRANSACTION_pk PRIMARY KEY (IDPARTICIPANTTRANSACTION)
  );

ALTER TABLE PARTICIPANTSTRANSACION
ADD CONSTRAINT FK_PT_IDUSER
FOREIGN KEY (IDUTILISATEUR) REFERENCES UTILISATEUR(UniqueID);

ALTER TABLE PARTICIPANTSTRANSACION
ADD CONSTRAINT FK_PT_IDTransaction
FOREIGN KEY (IDTRANSACTION) REFERENCES TRANSACTION(IDTRANSACTION);


CREATE SEQUENCE idparticipantstransaction_seq;


CREATE OR REPLACE TRIGGER PARTICIPANTSTRANSACION_TRG_SEQ
  BEFORE INSERT ON PARTICIPANTSTRANSACION
  FOR EACH ROW
BEGIN
  SELECT idparticipantstransaction_seq.nextval
  INTO :new.IDPARTICIPANTTRANSACTION
  FROM dual;
END;